### ISSUE TITLE
osx 10.9 opencv build error

### ISSUE THREAD

**Issue by kaylalewis** [mrnugget/opencv-haar-classifier-training#6] opened 2015-02-09 21:37 UTC
Hi,

I've followed the instructions, but I'm receiving the following errors on step 6 when attempting to compile the mergevec app. 

I've built the open cv distribution successfully but I'm still receiving these errors.

It seems like g++ can't find opencv.

```
mergevec.cpp:1:10: fatal error: 'cv.h' file not found
#include <cv.h>
         ^
1 error generated.
In file included from cvboost.cpp:64:
./_cvcommon.h:45:10: fatal error: 'opencv2/core/core.hpp' file not found
#include "opencv2/core/core.hpp"
         ^
1 error generated.
In file included from cvcommon.cpp:42:
./_cvcommon.h:45:10: fatal error: 'opencv2/core/core.hpp' file not found
#include "opencv2/core/core.hpp"
         ^
1 error generated.
In file included from cvsamples.cpp:49:
In file included from ./_cvhaartraining.h:51:
./_cvcommon.h:45:10: fatal error: 'opencv2/core/core.hpp' file not found
#include "opencv2/core/core.hpp"
         ^
1 error generated.
In file included from cvhaarclassifier.cpp:48:
In file included from ./_cvhaartraining.h:51:
./_cvcommon.h:45:10: fatal error: 'opencv2/core/core.hpp' file not found
#include "opencv2/core/core.hpp"
         ^
1 error generated.
In file included from cvhaartraining.cpp:49:
In file included from ./_cvhaartraining.h:51:
./_cvcommon.h:45:10: fatal error: 'opencv2/core/core.hpp' file not found
#include "opencv2/core/core.hpp"
         ^
1 error generated.
```

**Comment by mrnugget** [comment] 2015-02-11 06:03
That's weird. It worked for me just a couple of weeks ago on OS X.

Yeah, g++ can't find OpenCV in your output. Did you check what the pkg-config line returns? Do you have opencv installed? In a standard location or somewhere else?

**Comment by brannondorsey** [comment] 2015-02-11 18:55
Hi there, I've been helping @kaylalewis install and use this awesome package. We cloned and successfully built the version of openCV you mentioned in the README. Once we downloaded openCV to `~/` we moved into the root openCV directory and ran:
```
cmake # which successfully generated build files
make -j8
make install
```
Which built openCV binaries. Would this have also built and installed the necessary lib files (like opencv2) to `$PATH`?

**Comment by mrnugget** [comment] 2015-02-12 05:38
As far as I know, lib files don't get moved into `$PATH`, only executables should. And I don't know what the `make install` step of OpenCV does exactly.

What needs to happen is g++ getting the correct `-I` and `-l` flags passed to it. It also needs the correct `dylib` files (on OS X) to compile. In the instructions I use `pkg-config` for that. The output of `pkg-config` looks like this on my machine:

```
$ pkg-config --libs --cflags opencv | sed 's/libtbb\.dylib/tbb/'
-I/usr/local/Cellar/opencv/2.4.9/include/opencv -I/usr/local/Cellar/opencv/2.4.9/include /usr/local/Cellar/opencv/2.4.9/lib/libopencv_calib3d.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_contrib.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_core.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_features2d.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_flann.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_gpu.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_highgui.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_imgproc.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_legacy.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_ml.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_nonfree.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_objdetect.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_ocl.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_photo.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_stitching.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_superres.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_ts.a /usr/local/Cellar/opencv/2.4.9/lib/libopencv_video.dylib /usr/local/Cellar/opencv/2.4.9/lib/libopencv_videostab.dylib -ltbb
```

So if you can reproduce this with your manual OpenCV installation it should work.

**Comment by brannondorsey** [comment] 2015-02-13 20:24
I am now trying to build on my OSX 10.10 machine (following the same steps in the README) and I am also receiving errors on step 6. `pkg-config --libs --cflags opencv | sed 's/libtbb\.dylib/tbb/'` output is:
```
-I/usr/local/Cellar/opencv/2.4.9/include/opencv 
-I/usr/local/Cellar/opencv/2.4.9/include 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_calib3d.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_contrib.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_core.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_features2d.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_flann.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_gpu.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_highgui.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_imgproc.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_legacy.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_ml.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_nonfree.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_objdetect.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_ocl.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_photo.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_stitching.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_superres.dylib
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_ts.a 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_video.dylib 
/usr/local/Cellar/opencv/2.4.9/lib/libopencv_videostab.dylib 
```

which, to spare you the comparison, is exactly the output of yours excluding the `-ltbb` flag which errors with `library not found`. The main error is that `-lopencv_core` isn't found, which is strange because I have the dylib installed in a place where pkg-config can find it. Any thoughts?

**Comment by mrnugget** [comment] 2015-02-14 11:35
I actually have no idea. You're basically running the same setup as I do.

But it's not pkg-config that needs to find the library, it's g++ that needs access. pkg-config only provides us with the flags to pass to g++ so it can find the libraries.

Just a quick guess: is your g++ command correctly constructed?

**Comment by mrnugget** [comment] 2015-03-29 08:55
I'm closing this for now.

**Closed by mrnugget** 2015-03-29 08:55 UTC

**Comment by bogong17** [comment] 2016-03-20 02:03
Hey guys, I got the same error..
Did you fix it?
Thank you so much///

**Comment by arturgrigor** [comment] 2016-05-17 09:06
I had lots of issues with building the `mergevec` tool on OS X Yosemite but I've managed to fix them like this:

```bash
g++ `pkg-config --libs --cflags opencv` -I. -I/usr/local/Cellar/opencv/2.4.12_2/include/opencv -I/usr/local/Cellar/opencv/2.4.12_2/include -o mergevec mergevec.cpp\
  cvboost.cpp cvcommon.cpp cvsamples.cpp cvhaarclassifier.cpp\
  cvhaartraining.cpp cvsamplesoutput.cpp\
  -L/usr/local/Cellar/opencv/2.4.12_2/lib\
  -lopencv_core -lopencv_calib3d -lopencv_imgproc -lopencv_highgui -lopencv_objdetect
```

**Notes**
- The `opencv` package has been installed using Homebrew and the installed version was 2.4.12
- You need to run `export DYLD_LIBRARY_PATH=/usr/local/lib` in case you run into this error `ld: library not found for -llibtbb.dylib`
- `-I/usr/local/Cellar/opencv/2.4.12_2/include/opencv -I/usr/local/Cellar/opencv/2.4.12_2/include` is needed in case of this error `mergevec.cpp:1:10: fatal error: 'cv.h' file not found`
- You also need to include the `cvsamplesoutput.cpp` in case you run into this problem `JpgDatasetGenerator::JpgDatasetGenerator(char const*) in cvhaartraining-8f5a1b.o`

**Comment by sirajios** [comment] 2018-04-23 07:55
#46 #
Duplicate of 

> 

> 

> #
